name: Install D365 Field Service App

on:
  workflow_dispatch:

env:
  CLIENT_ID: 79623805-9f58-4b81-a1aa-81480ca86f44
  CLIENT_SECRET: 1Wj8Q~ihsJNRsUEdV9aZCbiExVoU3hKyw7O1BcFC
  TENANT_ID: 13588042-fe43-45bb-8ce1-83b2e6dd126c

jobs:
  install-field-service:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Field Service Application
        uses: microsoft/powerplatform-actions/install-application@main
        with:
          environment: https://operations-gesagenttest.crm4.dynamics.com
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ env.CLIENT_SECRET }}
          tenant-id: ${{ env.TENANT_ID }}
          application-list: .github/actions/create-environment/Applicationslist.json
          working-directory: .
