name: Create Dev Test and Prod Environments

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: "Name for the environment to be created"
        required: true
        default: environmentname
      
      client_id:
        description: "Service principal client id"
        required: true
        default: client_id
      
      user_id:
        description: "AAD object id for the user"
        required: true
        default: aad_object_id

jobs:
  Create-Environments:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Create Test Environment
        uses: microsoft/powerplatform-actions/create-environment@v1
        with:
          app-id: ${{ secrets.SOURCE_CLIENT_ID }}
          client-secret: ${{ secrets.SOURCE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.SOURCE_TENANT_ID }}
          name: ${{ github.event.inputs.env_name }}_Test
          type: Sandbox
          domain: ${{ github.event.inputs.env_name }}Test

      - name: Assign user to test environment
        uses: microsoft/powerplatform-actions/assign-user@v1
        with:
          app-id: ${{ secrets.SOURCE_CLIENT_ID  }}
          client-secret: ${{ secrets.SOURCE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.SOURCE_TENANT_ID }}
          environment: https://${{ github.event.inputs.env_name }}.crm.dynamics.com
          user: ${{ github.event.inputs.user_id }}
          role: System Administrator
