name: Create Dev Test and Prod Environments

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: "Name for the environment to be created"
        required: true
        default: environmentname

      client_id:
        description: "Service principal client id"
        required: true
        default: client_id

      user_id:
        description: "AAD object id for the user"
        required: true
        default: aad_object_id

jobs:
  create-environments:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Create Power Platform Environment
        uses: ./.github/actions/create-environment
        with:
          app-id: ${{ github.event.inputs.client_id }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          name: ${{ github.event.inputs.env_name }}
          region: unitedstates
          type: Sandbox
