name: Create Power Platform Environment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-env:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1.9.1

      - name: Create Power Platform Environment
        uses: microsoft/powerplatform-actions/create-environment@v1
        with:
          # --- Authentication (Service Principal) ---
          app-id: ${{ secrets.PP_APP_ID }}
          client-secret: ${{ secrets.PP_CLIENT_SECRET }}
          tenant-id: ${{ secrets.SOURCE_TENANT_ID }}

          # --- Environment Properties ---
          name: 'GitTest'          # environment unique name
          type: 'Sandbox'                   # Sandbox | Production | Trial
          region: 'northamerica'            # e.g., northamerica, europe, unitedkingdom
          domain: 'avanaded365test01'           # must be unique subdomain
          #user: ${{ secrets.PP_ADMIN_USERNAME }} # owner (UPN) of environment

          # Optional properties
          currency: 'USD'
          language: '1033'                  # English
          # templates: 'CDS'
          # team-id: '<AzureAD-Team-GUID>'
          # security-group-id: '<AAD-SecurityGroup-GUID>'
