name: Export and Import Solution

on:
  workflow_dispatch:

jobs:
  export-import:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install PAC CLI
      - name: powerplatform-actions
        uses: microsoft/powerplatform-actions@v1.9.1

      # Authenticate to Source using Service Principal
      - name: Auth to Source Environment
        run: |
          "${{ env.POWERPLATFORMTOOLS_PACPATH }}" auth create ^
            --url "https://operations-gesagenttest.crm4.dynamics.com/" ^
            --tenant "${{ secrets.SOURCE_TENANT_ID }}" ^
            --applicationId "${{ secrets.SOURCE_CLIENT_ID }}" ^
            --clientSecret "${{ secrets.SOURCE_CLIENT_SECRET }}"

      # Export solution from source
      - name: Export Solution
        run: |
          "${{ env.POWERPLATFORMTOOLS_PACPATH }}" solution export ^
            --path ./test.zip ^
            --name "test" ^
            --managed false ^
            --overwrite

      # Authenticate to Target using Service Principal
      - name: Auth to Target Environment
        run: |
          "${{ env.POWERPLATFORMTOOLS_PACPATH }}" auth create ^
            --url "https://TARGET_ENV.crm.dynamics.com" ^
            --tenant "${{ secrets.TARGET_TENANT_ID }}" ^
            --applicationId "${{ secrets.TARGET_CLIENT_ID }}" ^
            --clientSecret "${{ secrets.TARGET_CLIENT_SECRET }}"

      # Import solution to target
      - name: Import Solution
        run: |
          "${{ env.POWERPLATFORMTOOLS_PACPATH }}" solution import ^
            --path ./aSolution.zip ^
            --publish-changes true
