name: Power Platform Deploy Package

on:
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Power Platform Tools
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1.9.1

      # Step 3: Download Package from JFrog Artifactory
      - name: Download Package from JFrog Artifactory
        shell: pwsh
        env:
          JFROG_URL: https://trial5vsdtk.jfrog.io/artifactory/tf-trial/PackageAssets.zip!/TemplatePackage.dll
          JFROG_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}
        run: |
          $url    = $env:JFROG_URL
          $output = Join-Path $env:GITHUB_WORKSPACE 'TemplatePackage.dll'
          $headers = @{ Authorization = "Bearer $($env:JFROG_ACCESS_TOKEN)" }

          Invoke-WebRequest -Uri $url -Headers $headers -OutFile $output -ErrorAction Stop

          if (!(Test-Path $output) -or ((Get-Item $output).Length -eq 0)) {
            throw "Download failed or file is empty."
          }

      # Step 4: WhoAmI Action
      - name: WhoAmI Action
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ secrets.ENVIRONMENT_URL }}
          app-id: ${{ secrets.TARGET_CLIENT_ID }}
          client-secret: ${{ secrets.SOURCE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.SOURCE_TENANT_ID }}

      # Step 5: Deploy D365 FNO Package
      - name: Deploy D365 FNO Package
        uses: microsoft/powerplatform-actions/deploy-package@v1
        with:
          environment-url: ${{ secrets.ENVIRONMENT_URL }}
          app-id: ${{ secrets.TARGET_CLIENT_ID }}
          client-secret: ${{ secrets.SOURCE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.SOURCE_TENANT_ID }}
          package-path: "${{ github.workspace }}/TemplatePackage.dll"
          wait-for-completion: true
          max-async-wait-minutes: 60
