name: Import D365 Solutions in Stages

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to deploy'
        required: true
        default: ALMLab
      solution_version:
        description: 'Version of the solution to deploy (matches ZIP filename)'
        required: true
        default: 1.0.0.1
      source_branch:
        description: 'Branch containing exported solutions (PR merge branch or feature branch)'
        required: true
        default: master
      skip_managed_fut:
        description: 'Skip importing Managed solution to FUT environment?'
        required: false
        default: 'false'
      skip_unmanaged_sit:
        description: 'Skip importing Unmanaged solution to SIT environment?'
        required: false
        default: 'false'

env:
  CLIENT_ID: '79623805-9f58-4b81-a1aa-81480ca86f44'
  TENANT_ID: '13588042-fe43-45bb-8ce1-83b2e6dd126c'

permissions:
  contents: write

jobs:
  import-fut:
    name: Import Managed Solution FUT
    runs-on: windows-latest
    environment: FUT
    if: ${{ github.event.inputs.skip_managed_fut != 'true' }}
    steps:
      - name: Checkout source branch with exported solutions
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.source_branch }}

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1.9.1

      - name: Import Managed Solution to FUT
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: 'https://operations-gescopilottest.crm.dynamics.com/'
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ secrets.SOURCE_CLIENT_SECRET }}
          tenant-id: ${{ env.TENANT_ID }}
          solution-file: './out/exported/${{ github.event.inputs.solution_name }}-${{ github.event.inputs.solution_version }}-Managed.zip'
          import-as-managed: true

  import-sit:
    name: Import Unmanaged Solution SIT
    runs-on: windows-latest
    environment: SIT
    needs: import-fut
    if: ${{ github.event.inputs.skip_unmanaged_sit != 'true' }}
    steps:
      - name: Checkout source branch with exported solutions
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.source_branch }}

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1.9.1

      - name: Import Unmanaged Solution to SIT
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: 'https://operations-gescopilottest.crm.dynamics.com/'
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ secrets.SOURCE_CLIENT_SECRET }}
          tenant-id: ${{ env.TENANT_ID }}
          solution-file: './out/exported/${{ github.event.inputs.solution_name }}-${{ github.event.inputs.solution_version }}-Unmanaged.zip'
          import-as-managed: false
          publish-workflows: true
